---
keepalived_instances:
  patroni:
    interface: "eth0"
    state: 'MASTER'
    track_scripts:
      - patroni_vip_checker
    virtual_router_id: "11"
    priority: "150"
    vips:
      - "192.168.121.99/24 dev eth0"
  pdns:
    interface: "eth0"
    state: 'MASTER'
    track_files:
      - track_file weight -1
    virtual_router_id: "22"
    priority: "150"
    vips:
      - "192.168.121.98/24 dev eth0"
