---
keepalived_instances:
  internal:
    interface: "eth0"
    # You can also use your own variable to determine which node is master and who
    state: 'BACKUP'
    track_scripts:
      - patroni_vip_checker
    virtual_router_id: "1{{ groups['all'].index(inventory_hostname) }}"
    priority: "100"
    # Do not forget to define the VIPs, and their CIDR.
    vips:
      - "192.168.121.99/24 dev eth0"

# Whether to add {{ ansible_managed }} information on top of keepalived.conf
keepalived_show_ansible_managed: true

keepalived_scripts:
  patroni_vip_checker:
    fall: 1
    rise: 1
    interval: 1
    src_check_script: "{{ playbook_dir }}/patroni_vip_checker.sh"
    check_script: "/etc/keepalived/patroni_vip_checker.sh"

keepalived_global_defs:
  - script_user root
  - enable_script_security
