---
nginx_config_cleanup: true
nginx_config_cleanup_paths:
  - directory:
      - /etc/nginx/conf.d
    recurse: true

nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    config:
      servers:  # All previous modules are also available (when allowed) in the 'servers' and 'locations' contexts.
        - core:
            listen:
              - address: 0.0.0.0
                port: 80
                default_server: true
            server_name: "localhost"  # String or a list of strings -- Available only in the 'server' context
            index: index.html index.htm index.php  # Note -- This directive originally belongs to the NGINX index module, but we are making an exception here.
            root: "/home/pdnsadmin/PowerDNS-Admin/PowerDNS-Admin-0.4.2/powerdnsadmin"
            client_max_body_size: 10m
            client_body_buffer_size: 128k
          log:
            access:
              - path: /var/log/nginx/powerdns-admin-access.log
            error:
              - file: /var/log/nginx/powerdns-admin-error.log
          proxy:  # Configure proxy settings
            redirect: false
            connect_timeout: 60s
            send_timeout: 60s
            read_timeout: 90
            buffers:
              number: 8
              size: 4k
            buffer_size: 8k
            set_header:
              - field: Host
                value: $proxy_host
              - field: X-Real-IP
                value: $remote_addr
              - field: X-Forwarded-For
                value: $proxy_add_x_forwarded_for
          locations:
            - location: /
              proxy:
                pass: http://unix:/run/powerdns-admin/socket
                read_timeout: 120
                connect_timeout: 120
                redirect: off
            - location: ~ ^/static/
              core:
                include: /etc/nginx/mime.types
