---
# Dict containing all configuration options, except for the
# "config-dir", "setuid" and "setgid" directives in YAML format.
pdns_rec_config:
  allow-from: 192.168.121.0/24 # 0.0.0.0/0, 127.0.0.0/8, 10.0.0.0/8, 169.254.0.0/16, 192.168.0.0/16
  api-key: sshhApiKeyForRecursorHereShhh
  local-address: "0.0.0.0" # 0.0.0.0, 127.0.0.1,
  local-port: 53
  webserver: yes
  webserver-address: 0.0.0.0
  webserver-password: recursorWebPassword
  webserver-port: 8082
  trace: fail
  forward-zones: home.lab=127.0.0.1:5300
  forward-zones-recurse: .=1.1.1.1;8.8.8.8
