---
# Ddict containing all configuration options, except for backend
# configuration and the "config-dir", "setuid" and "setgid" directives.
pdns_config:
  allow-axfr-ips: 192.168.121.0/24
  local-address: 127.0.0.1
  local-port: 5300
  primary: yes
  api: yes
  api-key: SshhshhhhKeyHere
  webserver: yes
  webserver-address: 127.0.0.1
  webserver-allow-from: 127.0.0.0/8
  webserver-password: ssssshhhPassHere
  webserver-port: 8081

# A dict with all the backends you'd like to configure.
# This default starts just the bind-backend with an empty config file
pdns_backends:
  gpgsql:
    dbname: pdns
    host: "{{ ansible_default_ipv4.address }}"
    password: sshssshhhPassHerew
    port: 6432
    user: pdns
    dnssec: yes
