# PDNS API connection params
powerdns_auth_proxy_api_params:
  api-key: "{{ pdns_config['api-key'] }}"
  api-url: http://127.0.0.1:8081/api/v1/servers/localhost
  override-soa_edit_api: INCEPTION-INCREMENT
  override-nameservers: ns1.home.lab. ns2.home.lab.
  override-kind: Master
